### PR TITLE
Deployment with docker

### PR DESCRIPTION
**Pull request by tgxworld**

### CODE REVIEW

**Comment by tgxworld** [comment]
Need to figure out a way to cache bundler.

**Comment by thebengeu** [comment]
From skimming a few blog posts, seems easy enough for recent Docker versions. Could always do later on

**Comment by tgxworld** [comment]
@soedar Referenced your work here :stuck_out_tongue_closed_eyes:

**Comment by soedar** [comment]
:+1:

> Need to figure out a way to cache bundler.

My personal feeling is that we shouldn't cache bundler for production images, because production images should be self contained and have no dependencies on the actual machine. This would also make containers more portable to run on different machine, since each image becomes an actual snapshot of the application that is runnable directly on different machines.

Also, it might not be a good idea to run the build command on the production server. A better strategy would be to build the image in the CI (not sure if travis supports this) and push it to a Docker repository (eg DockerHub), and in production simply pull the image when there's an update.

**Comment by soedar** [comment]
Need to update README.md ? :stuck_out_tongue:

**Comment by thebengeu** [comment]
You could set Docker Hub to update the image whenever the repo is updated, no need for CI to do that.

**Comment by soedar** [comment]
Ah, nice. Good to know. :)

**Pull request merged**
